version: "3.7"

services:
  app:
    build: ./app
    container_name: django-gunicorn
    restart: always
    env_file:
      - django.env
    volumes:
      - ./app/static:/app/static
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations --merge && python manage.py migrate &&  python manage.py collectstatic --noinput && gunicorn --workers=2 --bind=0.0.0.0:8000 myapp.wsgi:application"

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app/static:/static
    depends_on:
      - app
